# Generated by Django 5.2.4 on 2025-07-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('operator', models.CharField(max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('ghostdraft', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('deliverable_format', models.CharField(max_length=100)),
                ('export_options', models.CharField(max_length=255)),
                ('render_preview', models.BooleanField(default=False)),
                ('voice_eligible', models.BooleanField(default=False)),
                ('voice_transcript', models.TextField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='incident_response.action')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incident_response.incident'),
        ),
    ]
