# Generated by Django 5.2.4 on 2025-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_response', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
